---
- name: setup prometheus server
  hosts: prometheus-server
  tasks:

  - name: Add prometheus repository
    yum_repository:
      name: prometheus
      baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
      description: prometheus repositry for centos
      gpgcheck: yes
      gpgkey:
        - https://packagecloud.io/prometheus-rpm/release/gpgkey
        - https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
      enabled: yes
      metadata_expire: 300

  - name: Install proemtheus and node-exporter
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - prometheus2
      - node_exporter

  - name: Start service prometheus and node-exporter
    systemd:
      name: "{{ item }}"
      state: started
    with_items:
      - prometheus
      - node_exporter
  - name: enable prometheus web portal on firewalld
    firewalld:
      port: 9090/tcp
      permanent: yes
      state: enabled
  - name: enable node_exporter on firewalld
    firewalld:
      port: 9100/tcp
      permanent: yes
      state: enabled
