---
- name: Install Utilization Packages
  hosts: all
  tasks:

  - name: yum install utilz
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - gcc
      - make
      - golang
