---
- name: setup docker on centos8
  hosts: docker
  tasks:
  - name: setup repository
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - yum-utils

  - name: Remove old docker
    yum:
      name: "{{ package }}"
      state: absent
    vars:
      package:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

  - name: add docker repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: install docker
    command: yum install -y --nobest docker-ce docker-ce-cli containerd.io

  - name: enable docker service
    systemd:
      state: started
      name: docker
      enabled: yes
