---
- name: Setup Nginx from Official Repository
  hosts: nginx
  tasks:
  - name: Add Nginx Mainline Repository
    yum_repository:
      name: nginx-mainline
      description: Nginx Mainline repo
      baseurl: https://nginx.org/packages/mainline/centos/8/$basearch/
      enabled: yes
  - name: Install Nginx Mainline
    yum:
      name: nginx
      enablerepo: nginx-mainline
      state: latest
  - name: Start nginx service
    systemd:
      name: nginx
      state: started
